Extranet_Intranet-master/ProjetoIntranet/Models/Entity/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjetoIntranet.Models.Entity
{
    public class Usuario
    {
        public int id { get; set; }

        [Required(ErrorMessage ="Nome obrigatório")]
        public string nome { get; set; }
        [Required(ErrorMessage = "Cargo obrigatório")]
        public string cargo { get; set; }
        [Required(ErrorMessage = "Login obrigatório")]
        public string usuarioLogin { get; set; }
        [Required(ErrorMessage = "Senha obrigatória")]
        public string senha { get; set; }
        
        public string centroCusto { get; set; }
        [Required(ErrorMessage = "Email obrigatório")]
        public string email { get; set; }

        public string bU { get; set; }
        [Required(ErrorMessage = "Setor obrigatório")]
        public string setor { get; set; }

        public Boolean situacao { get; set; }

        public String privilegios { get; set; }

        private List<GrupoUsuario> grupos = new List<GrupoUsuario>();

        public List<GrupoUsuario> getGrupos()
        {
            
            return grupos;
        }
        
        public void setGrupos(GrupoUsuario gu)
        {

            grupos.Add(gu);

        }

    }
}

Extranet_Intranet-master/ProjetoIntranet/Controllers/UsuarioController.cs
using ProjetoIntranet.Models.BO;
using ProjetoIntranet.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ProjetoIntranet.Helpers;

namespace ProjetoIntranet.Controllers
{
    [AutorizacaoCustomizada]
    public class UsuarioController : BaseController
    {

        private static IList<SelectListItem> users = new List<SelectListItem>();

        private static  IList<SelectListItem> itens = new List<SelectListItem>();

        private static IList<Usuario> usuarios = null;

        private static int contagemAnterior = 0;

        [AllowAnonymous]
        public ActionResult SetCulture(string culture, string View)
        {

            culture = CultureHelper.GetImplementedCulture(culture);

            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);

            switch (View)
            {
                case "Associar":
                    return RedirectToAction("Associar");

                case "DesativarUsuario":
                    return RedirectToAction("DesativarUsuario");

                case "CadastroUsuario":
                    return RedirectToAction("CadastroUsuario");

                default: return RedirectToAction("Principal", "Home");

            }

        }

        [HttpPost]
        [AutorizacaoCustomizada(Roles ="ADMINISTRADOR")]
        public ActionResult CadastroUsuario(Usuario user)
        {

            if (ModelState.IsValid)
            {

                UsuarioBO ubo = new UsuarioBO();
                ubo.Gravar(user);

                


            }


            return RedirectToAction("CadastroUsuario");
        }


        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR")]
        public ActionResult CadastroUsuario()
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;

            return View();
        }

        

        [HttpPost]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR")]
        public ActionResult Associar(FormCollection form)
        {

            bool isFormOk = ValidacaoForm(form);

            if (isFormOk)
            {
                var idUsuario = form["Lista"];
                var idGrupos = form["check"];

                String[] idGruposAssociados = idGrupos.Split(',');



                UsuarioEGruposBO ueg = new UsuarioEGruposBO();

                ueg.Gravar(idUsuario, idGruposAssociados);

               

            }
            
            ViewBag.users = users;
            ViewBag.lista = itens;


            return View();
        }

        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR")]
        public ActionResult Associar()
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;


            GrupoUsuarioBO gub = new GrupoUsuarioBO();

            UsuarioBO ubo = new UsuarioBO();


                users.Clear();
                itens.Clear();

            ViewBag.UsuarioLogado = usr.nome;

            //if ((users.Count <=0 && itens.Count <= 0)|| contagemAnterior != users.Count)
            //{


            //    users.Clear();
            //    itens.Clear();

              

               


            //    contagemAnterior = itens.Count;
            //}

            foreach (var obj1 in ubo.ListarUsuarios())
            {


                users.Add(new SelectListItem { Text = obj1.nome, Value = obj1.id.ToString() });

            }

            foreach (var obj in gub.ListarGrupos())
            {

                itens.Add(new SelectListItem { Text = obj.nome, Value = obj.id.ToString() });


            }

            ViewBag.users = users;
            ViewBag.lista = itens;

            

            return View();
        }
                

        private bool ValidacaoForm(FormCollection f)
        {

            bool retorno = true;
            var idUsuario = f["Lista"];
            var idGrupos = f["check"];
            ViewBag.users = users;
            ViewBag.lista = itens;

            if (idUsuario.Equals(""))
            {
                retorno = false;
                ViewData["msg1"] = "Escolha um funcionario!!";

            }

            if (idGrupos == null)
            {
                retorno = false;
                ViewData["msg2"] = "Escolha um Grupo!!";
            }


            return retorno;
        }

        
        

        [AutorizacaoCustomizada(Roles ="ADMINISTRADOR")]
        [HttpGet]
        public ActionResult DesativarUsuario(int ? pagina)
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;



            ViewBag.UsuarioLogado = usr.nome;

            int tamanhoPagina = 4;
            int numeroPagina = pagina ?? 1;

            UsuarioBO uBO = new UsuarioBO();

            usuarios = uBO.ListarUsuarios();

            TempData["listaDeUsuarios"] = usuarios;

            return View(usuarios.ToPagedList(numeroPagina,tamanhoPagina));
        }
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR")]
        [HttpPost]
        public ActionResult DesativarUsuario(int? pagina, FormCollection form,String id)
        {



            int userID = Convert.ToInt32(id);

            UsuarioBO uBO = new UsuarioBO();
            uBO.Desativar(userID);



            return View(TempData["listaDeUsuarios"] as IList<Usuario>);
        }

        [HttpPost]
        public ActionResult AtivarUsuario(int? pagina, FormCollection form, String id)
        {

            int userID = Convert.ToInt32(id);

            UsuarioBO uBO = new UsuarioBO();
            uBO.Ativar(userID);


            return View("DesativarUsuario", TempData["listaDeUsuarios"] as IList<Usuario>);
        }


    }
}

Extranet_Intranet-master/ProjetoIntranet/Views/Usuario/Associar.cshtml
@model ProjetoIntranet.Models.Entity.Usuario
@Recursos.Resources.Culture

@{
    ViewBag.Title = "Associar";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@helper selected(string c, string culture, string View = "Associar")
{
if (c == culture)
{
        @:checked="checked"
    }
}

<div class="row">
    @using (Html.BeginForm("SetCulture", "Usuario", new { View = "Associar" }))
    {

        <div id="language-icons" class="col-md-offset-10 col-sm-offset-10">
            <button href="" id="pt-Br" value="pt-Br" selected("pt-Br", culture) name="culture" type="submit">
                <img src="~/Resources/pt_br.png" alt="ícone bandeira Brasileira" title="@Recursos.Resources.Portugues" type="submit" />

            </button>
            <button href="" id="en-us" value="en-us" selected("en-us", culture) type="submit" name="culture">
                <img src="~/Resources/en_us.png" alt="ícone bandeira Americana" title="@Recursos.Resources.Ingles" type="submit" />
            </button>
        </div>
    }
</div>
<h2>@Recursos.Resources.AssociarUsuario</h2>



<div>
    @using (Html.BeginForm("Associar", "Usuario", FormMethod.Post))
    {
        @Html.AntiForgeryToken();
        @Html.ValidationSummary()

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@Recursos.Resources.EscolhaUsuario</h3>
            </div>
            <div class="panel-body">


                @Html.Label(Recursos.Resources.Usuario, new { @for = "Usuario" })
                @Html.DropDownList("Lista", (IEnumerable<SelectListItem>)ViewBag.users, "Selecione um Usuário", new { @onchange= "verificar()" })
                <br>
                <span class="text-danger"> @ViewBag.msg1 </span>

            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@Recursos.Resources.GruposExistentes</h3>
            </div>
            <div class="panel-body">


                @foreach (var item in ViewBag.lista)
                {
                    <div class="input-group">

                        <span class="checkbox">

                            <label>
                                <input type="checkbox" name="check" id="check" value="@item.Value" /><b>@item.Text</b>
                            </label>

                        </span>

                    </div>
                    

                }
                <br>
                <span class="text-danger"> @ViewBag.msg2 </span>
            </div>
        </div>




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@Recursos.Resources.Salvar" class="btn btn-success" />
                    <input type="reset" value="@Recursos.Resources.Cancelar" class="btn btn-danger" /><br>
                </div>
            </div>
    }
</div>

Extranet_Intranet-master/ProjetoIntranet/Views/Usuario/CadastroUsuario.cshtml
@model ProjetoIntranet.Models.Entity.Usuario
@Recursos.Resources.Culture

@{
    ViewBag.Title = "CadastroUsuario";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@helper selected(string c, string culture, string View = "CadastroUsuario")
{
if (c == culture)
{
        @:checked="checked"
    }
}

<div class="row">
    @using (Html.BeginForm("SetCulture", "Usuario", new { View = "CadastroUsuario" }))
    {

        <div id="language-icons" class="col-md-offset-10 col-sm-offset-10">
            <button href="" id="pt-Br" value="pt-Br" selected("pt-Br", culture) name="culture" type="submit">
                <img src="~/Resources/pt_br.png" alt="ícone bandeira Brasileira" title="@Recursos.Resources.Portugues" type="submit" />

            </button>
            <button href="" id="en-us" value="en-us" selected("en-us", culture) type="submit" name="culture">
                <img src="~/Resources/en_us.png" alt="ícone bandeira Americana" title="@Recursos.Resources.Ingles" type="submit" />
            </button>
        </div>
    }
</div>

<h2>@Recursos.Resources.CadastrarUsuario</h2>

@using (Html.BeginForm("CadastroUsuario","Usuario",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label(Recursos.Resources.Nome, new { @class = "control-label col-md-2", @for="nome"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.Cargo, new { @class = "control-label col-md-2", @for = "cargo" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.LoginUsuario, new { @class = "control-label col-md-2", @for = "usuarioLogin" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.usuarioLogin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.usuarioLogin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.Senha, new { @class = "control-label col-md-2", @for = "senha" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.senha, new { htmlAttributes = new { @class = "form-control" ,@type ="password" } })
                @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.centroCusto, new { @class = "control-label col-md-2", @for = "centroCusto" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.centroCusto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.centroCusto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.Email, new { @class = "control-label col-md-2", @for = "email" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.BU, new { @class = "control-label col-md-2", @for = "bU" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.Setor, new { @class = "control-label col-md-2", @for = "setor" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.setor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.setor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(Recursos.Resources.situacao, new { @class = "control-label col-md-2", @for = "situacao" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.situacao)
                    @Html.ValidationMessageFor(model => model.situacao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Recursos.Resources.Salvar" class="btn btn-success" /><br>
            </div>
        </div>
    </div>
}

Extranet_Intranet-master/ProjetoIntranet/Views/Usuario/DesativarUsuario.cshtml
@model IEnumerable<ProjetoIntranet.Models.Entity.Usuario>
@Recursos.Resources.Culture

@{
    ViewBag.Title = "DesativarUsuario";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@helper selected(string c, string culture, string View = "DesativarUsuario")
{
if (c == culture)
{
        @:checked="checked"
    }
}

<div class="row">
    @using (Html.BeginForm("SetCulture", "Usuario", new { View = "DesativarUsuario" }))
    {

        <div id="language-icons" class="col-md-offset-10 col-sm-offset-10">
            <button href="" id="pt-Br" value="pt-Br" selected("pt-Br", culture) name="culture" type="submit">
                <img src="~/Resources/pt_br.png" alt="ícone bandeira Brasileira" title="@Recursos.Resources.Portugues" type="submit" />

            </button>
            <button href="" id="en-us" value="en-us" selected("en-us", culture) type="submit" name="culture">
                <img src="~/Resources/en_us.png" alt="ícone bandeira Americana" title="@Recursos.Resources.Ingles" type="submit" />
            </button>
        </div>
    }
</div>

<h2>@Recursos.Resources.DesativarAtivar</h2>


<div class="container" style="overflow-x:scroll">

    <table class="table">
        <tr>
            <th>
                @Html.DisplayName(@Recursos.Resources.Nome)
            </th>
            <th>
                @Html.DisplayName(@Recursos.Resources.Cargo)
            </th>
            <th>
                @Html.DisplayName(@Recursos.Resources.LoginUsuario)
            </th>

            <th>
                @Html.DisplayName(@Recursos.Resources.centroCusto)
            </th>
            <th>
                @Html.DisplayName(@Recursos.Resources.Email)
            </th>
            <th>
                @Html.DisplayName(@Recursos.Resources.BU)
            </th>
            <th>
                @Html.DisplayName(@Recursos.Resources.Setor)
            </th>
            <th>
                @Html.DisplayName(@Recursos.Resources.Ativo)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cargo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.usuarioLogin)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.centroCusto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.bU)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.setor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.situacao)
                </td>

                <td>

                    @*@Html.ActionLink(" ", "AtivarUsuario", "Usuario", new { id = item.id, @class = "btn btn-primary glyphicon glyphicon-ok" })*@

                    <button type="button" id="@item.id" class="btn btn-primary glyphicon glyphicon-ok ativar" title="clique para ativar usuário"></button>

                    @*@Html.ActionLink(" ", "DesativarUsuario", "Usuario", new { id=item.id, @class = "btn btn-danger glyphicon glyphicon-remove" })*@

                    <button type="button" id="@item.id" class="btn btn-danger glyphicon glyphicon-remove desativar" title="clique para desativar usuário"></button>
                </td>
            </tr>
        }

    </table>

</div>



<div class="container ajuda">
    <div class="modal fade" id="feedbackAtivado" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


                <div class="alert alert-success" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    <b>Usuário ativado  com sucesso!</b>
                </div>



            </div>
        </div>
    </div>
</div>

<div class="container ajuda">
    <div class="modal fade" id="feedbackDesativado" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


                <div class="alert alert-success" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    <b>Usuário desativado  com sucesso!</b>
                </div>



            </div>
        </div>
    </div>
</div>