Extranet_Intranet-master/ProjetoIntranet/Controllers/PostagensController.cs
using ProjetoIntranet.Models.BO;
using ProjetoIntranet.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.IO;
using PagedList;
using ProjetoIntranet.MV;
using ProjetoIntranet.Helpers;
using System.Web;

namespace ProjetoIntranet.Controllers
{
    [AutorizacaoCustomizada]
    public class PostagensController : BaseController
    {
        [AllowAnonymous]
        public ActionResult SetCulture(string culture, string View)
        {

            culture = CultureHelper.GetImplementedCulture(culture);

            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);

            switch (View)
            {
                case "CriarPostagem":
                    return RedirectToAction("CriarPostagem");

                case "ListarPostagens":
                    return RedirectToAction("ListarPostagens");

                case "ListarRascunhos":
                    return RedirectToAction("ListarRascunhos");

                case "ListarPostagensPrincipal":
                    return RedirectToAction("LIstarPostagensPrincipal");

                case "ListarPorDataRascunhos":
                    return RedirectToAction("ListarPorDataRascunhos");

                case "ListarPorTituloRascunhos":
                    return RedirectToAction("ListarPorTituloRascunhos");

                case "ListarPorDataPostagens":
                    return RedirectToAction("ListarPorDataPostagens");

                case "ListarPorTituloPostagens":
                    return RedirectToAction("ListarPorTituloPostagens");

                case "EditarRascunho":
                    return RedirectToAction("EditarRascunho");

                default: return RedirectToAction("Principal","Home");

            }

        }

        [HttpPost]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult CriarPostagem(Postagem post, FormCollection form, Imagem arq )
        {
           
            Imagem img = new Imagem();
            List<Imagem> lista = new List<Imagem>();
            var dataHora = DateTime.Now;

           var x = form["checkbox"];

            if (form["checkbox"] == null)
            {
                post.rascunho = 0;
            }
            else
            {
                post.rascunho = 1;
            }

            foreach (var imagem in arq.imagens)
            {
                if (imagem != null && imagem.ContentLength > 0)
                {
                    var extensoePermitidas = new String[] { ".jpg", ".jpeg", ".png" };

                    var checarExtensao = Path.GetExtension(imagem.FileName).ToLower();

                    var tipo = Path.GetExtension(imagem.FileName).ToLower();

                    if (extensoePermitidas.Contains(checarExtensao))
                    {
                        string caminho = Path.Combine(Server.MapPath("~/imagens"), Path.GetFileName(imagem.FileName));
                        imagem.SaveAs(caminho);

                        img.imagem = System.IO.File.ReadAllBytes(caminho);
                        img.nome = imagem.FileName;
                        img.tipoArquivo = imagem.ContentType;

                        lista.Add(img);
                        img = new Imagem();

                        

                    }
                    else {

                       

                        ViewData["sucesso"] = 1;

                    }
                  

                }

            }

            PostagemBO postagemBO = new PostagemBO();

            int id = postagemBO.Gravar(post, dataHora, post.rascunho); // colocar um tste de condição aqui


            Postagem postagem = postagemBO.ReadById(id);

            int postagem_fk = postagem.id;

           

                ImagemBO imagemBO = new ImagemBO();

            imagemBO.Gravar(lista, arq, postagem_fk);
            
            return RedirectToAction("CriarPostagem");

        }

        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult CriarPostagem()
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;


            return View();
        }

        [HttpPost]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult EditarRascunho(Postagem rascunho, Imagem arq, FormCollection form)
        {
            PostagemBO postagemBO = new PostagemBO();
            Imagem img = new Imagem();


            List<Imagem> lista = new List<Imagem>();

            var dataEnvio = DateTime.Now;

            //pegando o valor do campo rascunho  e do id da postagem
            Postagem postagem = new Postagem();
            int post = postagem.rascunho;
            int id = postagem.id;

            foreach (var imagem in arq.imagens) // colocar em um metodo
            {
                if (imagem != null && imagem.ContentLength > 0)
                {
                    var extensoePermitidas = new String[] { ".jpg", ".jpeg", ".png" };

                    var checarExtensao = Path.GetExtension(imagem.FileName).ToLower();

                    var tipo = Path.GetExtension(imagem.FileName).ToLower();

                    if (extensoePermitidas.Contains(checarExtensao))
                    {
                        string caminho = Path.Combine(Server.MapPath("~/imagens"), Path.GetFileName(imagem.FileName));
                        imagem.SaveAs(caminho);

                        img.imagem = System.IO.File.ReadAllBytes(caminho);
                        img.nome = imagem.FileName;
                        img.tipoArquivo = imagem.ContentType;
                        lista.Add(img);
                        img = new Imagem();

                    }
                    else
                    {
                        ViewBag.aviso = "arquivo com extensão inválida!";
                    }

                }

            }

            postagemBO.Alterar(rascunho, dataEnvio, lista, arq, id, post);
            return RedirectToAction("ListarRascunhos");

        }


        public JsonResult RascunhoID(int id)
        {

            PostagemBO pBO = new PostagemBO();

            var rascunho = pBO.ReadById(id);


            return Json(rascunho, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult EditarRascunho(FormCollection form,int id)
        {
            //int idPostagem = Convert.ToInt32(form["id"]);
            //TempData["IdRascunhos"] = idPostagem;
            //return View(idPostagem);

            Postagem postagem = new Postagem();
            PostagemBO postagemBO = new PostagemBO();
            postagem = postagemBO.ReadById(id);
            return View(postagem);

          
        }

        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult ExcluirRascunho(int id)
        {
            PostagemBO rascunhoBO = new PostagemBO();

            rascunhoBO.DeletePostagem(id);

            return RedirectToAction("ListarRascunhos");
        }

        [HttpPost]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult ExcluirRascunho(int id, FormCollection form)
        {
            PostagemBO rascunhoBO = new PostagemBO();

            rascunhoBO.DeleteRascunho(id);

            return RedirectToAction("ListarRascunhos");
        }

        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult ExcluirPostagem(int id)
        {
            PostagemBO rascunhoBO = new PostagemBO();

            rascunhoBO.DeletePostagem(id);

            return RedirectToAction("ListarPostagens");
        }


        [HttpPost]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult ExcluirPostagem(int id, FormCollection form)
        {
            PostagemBO rascunhoBO = new PostagemBO();

            rascunhoBO.DeletePostagem(id);

            return RedirectToAction("ListarPostagens");
        }

       


        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult ListarRascunhos(int? pagina)
        {
            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;

            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;


            PostagemBO postagemBO = new PostagemBO();
            IList<Postagem> rascunhos = postagemBO.ListarRascunhos();

           if(rascunhos == null)
            {
                return View("SemRascunho");

            }
            else
            {

                TempData["TitulosRascunhos"] = rascunhos;
                rascunhos.ToList();
                return View(rascunhos.ToPagedList(numeroPagina, tamanhoPagina));

            }

               
           
            

        }

               
        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,RECURSOSHUMANOS")]
        public ActionResult ListarPostagens(int? pagina)
        {
            int tamanhoPagina = 10;
            int numeroPagina = pagina ?? 1;
            
            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;

            PostagemBO postagemBO = new PostagemBO();
            List<Postagem> postagens = postagemBO.ListarPostagens();
            TempData["TitulosPostagens"] = postagens;

Extranet_Intranet-master/ProjetoIntranet/Views/Postagens/CriarPostagem.cshtml
@model ProjetoIntranet.Models.Entity.Postagem
@Recursos.Resources.Culture

@{
    ViewBag.Title = "CriarPostagem";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@helper selected(string c, string culture, string View = "CriarPostagem")
{
if (c == culture)
{
        @:checked="checked"
    }
}



<div class="row">
    @using (Html.BeginForm("SetCulture", "Postagens", new { View = "CriarPostagem" }))
    {
        <div id="language-icons" class="col-md-offset-10 col-sm-offset-10">
            <button href="" id="pt-Br" value="pt-Br" selected("pt-Br", culture) name="culture" type="submit">
                <img src="~/Resources/pt_br.png" alt="ícone bandeira Brasileira" title="@Recursos.Resources.Portugues" type="submit" />

            </button>
            <button href="" id="en-us" value="en-us" selected("en-us", culture) type="submit" name="culture">
                <img src="~/Resources/en_us.png" alt="ícone bandeira Americana" title="@Recursos.Resources.Ingles" type="submit" />
            </button>
        </div>
    }
</div>

<h2>@Recursos.Resources.CriarPostagem</h2>




@using (Html.BeginForm("CriarPostagem", "Postagens", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-group", @id = "form-postagem" }))
{
    <div class="form-group">
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()


        @Html.Label("titulo", Recursos.Resources.Titulo)
        @Html.TextBoxFor(x => x.titulo, new { @class = "form-control" })



        <br>


        @Html.Label("corpo", Recursos.Resources.Corpo)
        @Html.TextAreaFor(x => x.corpo, new { @class = "form-control" })



        <br>



        @Html.Label("etiqueta", Recursos.Resources.Etiqueta)

        <a data-toggle="modal" data-target="#helpModalTag"><span id="glyph-btn" class="glyphicon glyphicon-question-sign"> </span></a>

        @Html.TextBoxFor(x => x.etiqueta, new { @class = "form-control" })


        <br>

        <label for="file">@Recursos.Resources.EnviarImagens</label>
        <input type="file" name="imagens" id="imagens" multiple><br><br>

        <input type="checkbox" id="checkBox" name="checkbox"> @Recursos.Resources.Marcar
        <a data-toggle="modal" data-target="#helpModalPub2"><span id="glyph-btn" class="glyphicon glyphicon-question-sign"> </span></a>

        <br>
        <br>
        <button id="btn-enviar-postagem" type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok">@Recursos.Resources.Enviar </span>
        </button>




    </div>
}






<div class="container ajuda">
    <div class="modal fade" id="helpModalTag" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="alert alert-info" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Info:</span>
                    <b>Também conhecidas com TAGS,as etiquetas devem ser separadas por virgulas.</b>
                </div>


            </div>
        </div>
    </div>
</div>

<div class="container ajuda">
    <div class="modal fade " id="postagemOK" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


                <div class="alert alert-success" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Sucesso:</span>
                    <b>Salvo com sucesso!</b>
                </div>



            </div>
        </div>
    </div>
</div>



<div class="container ajuda">
    <div class="modal fade" id="helpModalPub2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


                <div class="alert alert-info" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Info:</span>
                    <b>Se esta opção estiver marcada,ao salvar a postagem , ela não será pulicada ainda,podendo ser publicada posteriormente</b>
                </div>



            </div>
        </div>
    </div>
</div>


<div class="container ajuda">
    <div class="modal fade" id="postagemVazia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


                <div class="alert alert-danger" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    <b>O formulário possui campos vazios!</b>
                </div>



            </div>
        </div>
    </div>
</div>



<div class="container ajuda">
    <div class="modal fade" id="erroUpload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


                <div class="alert alert-danger" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    <b>deu ruim!</b>
                </div>



            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Extranet_Intranet-master/ProjetoIntranet/Views/Postagens/EditarRascunho.cshtml
@model ProjetoIntranet.Models.Entity.Postagem
@Recursos.Resources.Culture

@{
    ViewBag.Title = "EditarRascunho";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@helper selected(string c, string culture, string View = "EditarRascunho")
{
if (c == culture)
{
        @:checked="checked"
    }
}



<div class="row">
    @using (Html.BeginForm("SetCulture", "Postagens", new { View = "EditarRascunho" }))
    {

        <div id="language-icons" class="col-md-offset-10 col-sm-offset-10">
            <button href="" id="pt-Br" value="pt-Br" selected("pt-Br", culture) name="culture" type="submit">
                <img src="~/Resources/pt_br.png" alt="ícone bandeira Brasileira" title="@Recursos.Resources.Portugues" type="submit" />

            </button>
            <button href="" id="en-us" value="en-us" selected("en-us", culture) type="submit" name="culture">
                <img src="~/Resources/en_us.png" alt="ícone bandeira Americana" title="@Recursos.Resources.Ingles" type="submit" />
            </button>
        </div>
    }
</div>

<h2>@Recursos.Resources.EditarRascunho</h2>

@using (Html.BeginForm("EditarRascunho", "Postagens", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-group" ,@id="formEditar"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.corpo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
                 @Html.TextAreaFor(model => model.corpo,  new { @class = "form-control" ,@id="txaCorpo" } )
                @Html.ValidationMessageFor(model => model.corpo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", @id ="tit" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.etiqueta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.etiqueta, new { htmlAttributes = new { @class = "form-control", @id ="etiq" } })
                @Html.ValidationMessageFor(model => model.etiqueta, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <br>
            <label for="file">@Recursos.Resources.EnviarImagens</label>
            <input type="file" name="imagens" id="imagens" multiple><br><br>
            <br>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="Salvar" class="btn btn-success" >
                <span class="glyphicon glyphicon-ok">@Recursos.Resources.Enviar </span></button>
            </div>
        </div>
    </div>
}

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Extranet_Intranet-master/ProjetoIntranet/Views/Postagens/ListarPorDataPostagens.cshtml
@model PagedList.IPagedList<ProjetoIntranet.Models.Entity.Postagem>
@using PagedList.Mvc
@using PagedList
@Recursos.Resources.Culture


@{
    ViewBag.Title = "ListarPorDataPostagens";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@helper selected(string c, string culture, string View = "ListarPorDataPostagens")
{
if (c == culture)
{
        @:checked="checked"
    }
}



<div class="row">
    @using (Html.BeginForm("SetCulture", "Postagens", new { View = "ListarPorDataPostagens" }))
    {

        <div id="language-icons" class="col-md-offset-10 col-sm-offset-10">
            <button href="" id="pt-Br" value="pt-Br" selected("pt-Br", culture) name="culture" type="submit">
                <img src="~/Resources/pt_br.png" alt="ícone bandeira Brasileira" title="@Recursos.Resources.Portugues" type="submit" />

            </button>
            <button href="" id="en-us" value="en-us" selected("en-us", culture) type="submit" name="culture">
                <img src="~/Resources/en_us.png" alt="ícone bandeira Americana" title="@Recursos.Resources.Ingles" type="submit" />
            </button>
        </div>
    }
</div>


<h2>@Recursos.Resources.PostagensCadastradas</h2>


<div class="row">

    @using (Html.BeginForm("ListarPorTituloPostagens", "Postagens", FormMethod.Post))
    {
        <p> <b>@Recursos.Resources.PesquisarTítulo</b></p>
        <div class="col-lg-8 col-md-8 col-sm-8">
            @Html.Label(@Recursos.Resources.PesquisarPorTítulo, new { @for = "titulo" })
            @Html.TextBox("titulo", null, new { @class = "form-control" })
        </div>

        <div class="col-lg-4 col-md-4 col-sm-4">

            <button type="submit" class="btn btn-success" style="margin-top:29px;" title="@Recursos.Resources.cliqueParaPesquisar"><span class="glyphicon glyphicon-search"> </span></button>

        </div>
    }
</div>

<div class="row">

    @using (Html.BeginForm("ListarPorDataPostagens", "Postagens", FormMethod.Post))
    {
        <p><b>@Recursos.Resources.PesquisarPorData</b></p>

        <div class="col-lg-8 col-md-8 col-sm-8">



            <div class="col-lg-6 col-md-6 col-sm-6">
                @Html.Label(@Recursos.Resources.DataInicial, new { @for = "dataInicial" })

                @Html.TextBox("dataInicial", null, new { @class = "form-control" })
            </div>

            <div class="col-lg-6 col-md-6 col-sm-6">

                @Html.Label(@Recursos.Resources.DataFinal, new { @for = "dataFim" })

                @Html.TextBox("dataFim", null, new { @class = "form-control" })
            </div>

        </div>

        <div class="col-lg-4 col-md-4 col-sm-4">

            <button type="submit" class="btn btn-success" style="margin-top:29px;" title="@Recursos.Resources.cliqueParaPesquisar"><span class="glyphicon glyphicon-search"> </span></button>

        </div>

    }

</div>
<br>

<div class="container" style="overflow-x:scroll">


    <div class="row">

        <table class="table">

            <tr>
                <th>
                    @Html.DisplayName(@Recursos.Resources.Numero)
                </th>
                <th>
                    @Html.DisplayName(Recursos.Resources.Corpo)
                </th>
                <th>
                    @Html.DisplayName(@Recursos.Resources.Titulo)

                </th>
                <th>
                    @Html.DisplayName(Recursos.Resources.Etiqueta)
                </th>
                <th>
                    @Html.DisplayName(Recursos.Resources.Imagens)
                </th>
            </tr>

            @foreach (var Postagem in Model)
            {
                using (Html.BeginForm("ExcluirPostagem", "Postagens", new { id = Postagem.id }))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => Postagem.id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Postagem.corpo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Postagem.titulo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Postagem.etiqueta)
                        </td>
                        <td>
                            @if (Postagem.imagensPostagens != null)
                            {
                                foreach (var itemImagem in Postagem.imagensPostagens)
                                {
                                    <br />
                                    <div class="item branding">
                                        <img src="data:image;base64, @System.Convert.ToBase64String(itemImagem.imagem)" width="150" height="30" />
                                    </div>
                                }
                            }

                        </td>

                        <td>

                            <button type="submit" class="btn btn-large btn btn-danger glyphicon glyphicon-trash" title="clique para apagar a postagem" id="Postagem.id" onclick="return confirm('deseja realmente excluir esta postagem?')"></button>

                        </td>

                    </tr>
                }
            }
        </table>
        Página @Model.PageNumber de @Model.PageCount
        @Html.PagedListPager(Model, Page => Url.Action("ListarPorDataPostagens", new { pagina = Page }))

    </div>

</div>

<div class="container">
    <div class="modal fade" id="feedbackExcluirPostagem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="alert alert-success" role="alert" style="margin-bottom:0px;">
                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    <b>Excluido com sucesso!</b>
                </div>

            </div>
        </div>
    </div>
</div>

Extranet_Intranet-master/ProjetoIntranet/Views/Postagens/ListarPostagensPrincipal.cshtml
@model PagedList.IPagedList<ProjetoIntranet.Models.Entity.Postagem>
@using PagedList.Mvc
@Recursos.Resources.Culture

@{
    ViewBag.Title = "ListarPostagensPrincipal";
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    Layout = null;
}

@helper selected(string c, string culture, string View = "ListarPostagensPrincipal")
{
if (c == culture)
{
        @:checked="checked"
    }
}


        <!DOCTYPE html>



        <html>
        <head>
            <meta name="viewport" content="width=device-width" />
            <title>ListarPostagensPrincipal</title>
        </head>
        <body>

            <div class="row">

                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">

                    @using (Html.BeginForm("ListarPostagensPrincipal", "Postagens", FormMethod.Post, new { @class = "form-inline", @id = "form-area" }))
                    {
                        <div id="form-group-area" class="form-group ">

                            @Html.Label(Recursos.Resources.Buscar, new { @for = "tag", @id = "tag" })

                            @Html.TextBox("tag", null, new { @class = "form-control" })

                        </div>


                        <button id="btn-submit-datas" type="submit" class="btn btn-success" title="clique para pesquisar"><span class="glyphicon glyphicon-search"> </span></button>
                    }

                </div>

            </div>





            <div class="panel-body ">

                @foreach (var item in Model)
                {



                    <div class="mensagem">

                        <div class="tituloPost">

                            <div class="col-md-4 col-sm-4 col-xs-4" style="padding-left:0px;">


                                <div class="abaEsquerda">  </div>

                            </div>

                            <div class="col-md-4 col-sm-4 col-xs-4 fundo-bloco" >
                                

                                <p style="text-align:center;"> @Html.DisplayFor(modelItem => item.titulo) </p>

                            </div>

                            <div class="col-md-4 col-sm-4 col-xs-4" style="padding-right:0px;">

                                <div class="abaDireita">   </div>

                            </div>


                        </div>

                        <br>

                        <div class="container">

                            @if (item.imagensPostagens != null)
                    {
                        foreach (var itemImagem in item.imagensPostagens)
                        {

                                    <div class="row">

                                        @*<div class="col-md-4 col-sm-3" style="height:20px;"> </div>

                                            <div class="col-md-4 col-sm-3" style="height:20px;">

                                            </div>*@

                                        <div class="col-md-12 col-sm-12 fundo-bloco">
                                            <img class="imagem" src="data:image;base64, @System.Convert.ToBase64String(itemImagem.imagem)">

                                        </div>

                                    </div>

                                }
                            }



                        </div>

                        <div class="textoPost" >   <p> @Html.DisplayFor(modelItem => item.corpo) </p>  </div>

                        <div class="rodapePost">

                            <hr class="hr-rodape">

                        </div>

                    </div>






                }
            </div>







            Página @Model.PageNumber de @Model.PageCount
            @Html.PagedListPager(Model, Page => Url.Action("ListarPostagens", new { pagina = Page }))
        </body>
    </html>