Extranet_Intranet-master/ProjetoIntranet/Controllers/GrupoUsuarioController.cs
using Newtonsoft.Json;
using ProjetoIntranet.Helpers;
using ProjetoIntranet.Models.BO;
using ProjetoIntranet.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoIntranet.Controllers
{
    [AutorizacaoCustomizada]
    public class GrupoUsuarioController : BaseController
    {

       private static List<SelectListItem> privilegios = new List<SelectListItem>();

        [AllowAnonymous]
        public ActionResult SetCulture(string culture, string View)
        {

            culture = CultureHelper.GetImplementedCulture(culture);

            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);

            switch (View)
            {
                case "CriarGrupo":
                    return RedirectToAction("CriarGrupo");

                case "ListarGrupos":
                    return RedirectToAction("ListarGrupos");
                                    
                default: return RedirectToAction("Principal", "Home");

            }

        }

        [HttpPost]
        public ActionResult CriarGrupo(String json )
        {
                       

           var grupoUsuario = JsonConvert.DeserializeObject<GrupoUsuario>(json);

            ViewBag.privilegios = privilegios;


            if (grupoUsuario.nome != "" && grupoUsuario.privilegios != "")
            {


                GrupoUsuarioBO gub = new GrupoUsuarioBO();

                gub.Gravar(grupoUsuario);

            }
            

                
                        
           

            return View();

        }


        [HttpGet]
        [AutorizacaoCustomizada(Roles ="ADMINISTRADOR")]
        public ActionResult CriarGrupo()
        {
            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;

            if (privilegios.Count == 0)
            {
                privilegios.Add(new SelectListItem { Text = "Administrador", Value = Privilegios.ADMINISTRADOR.ToString() });
                privilegios.Add(new SelectListItem { Text = "Tecnologia", Value = Privilegios.TECNOLOGIA.ToString() });
                privilegios.Add(new SelectListItem { Text = "Recursos Humanos", Value = Privilegios.RECURSOSHUMANOS.ToString() });
                privilegios.Add(new SelectListItem { Text = "Produção", Value = Privilegios.PRODUCAO.ToString() });
                privilegios.Add(new SelectListItem { Text = "Marketing", Value = Privilegios.MARKETING.ToString() });

            }
            

            ViewBag.privilegios = privilegios;

           
                       
                        
           

            return View();
        }

        

        [HttpGet]
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR")]
        public ActionResult ListarGrupos()
        {
            GrupoUsuarioBO gbo = new GrupoUsuarioBO();


            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;



            return View(gbo.ListarGrupos());

            

            
        }

        
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR")]
        public ActionResult Excluir(int id) // 
        {
            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;

            GrupoUsuario gu = new GrupoUsuario();
           

                gu.id = id;

                GrupoUsuarioBO gub = new GrupoUsuarioBO();


            Boolean NaoDeletado = gub.Delete(gu);
            
            if(NaoDeletado == true)
            {

                return Json(new { success = false, responseText = "Existe(m) usuario(s) associado(s) ao grupo!!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);

            }
            

           
        }
        [HttpPost]
        public ActionResult TesteId(GrupoUsuario gu)
        {

           

            return View();
        }


        [HttpGet]
        public ActionResult TesteId()
        {

            return View();
        }


        [HttpGet]
        public ActionResult Linkagem()
        {



            return View();
        }

        [HttpPost]
        public ActionResult Linkagem(int temp)// parametro temporario
        {



            return View();
        }



    }
}

Extranet_Intranet-master/ProjetoIntranet/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web.Mvc;

using Newtonsoft.Json;
using ProjetoIntranet.Models.Entity;

using System.IO;
using System.Web.UI;


using ProjetoIntranet.MV;
using ProjetoIntranet.Models.BO;
using ProjetoIntranet.Helpers;
using System.Web;

namespace ProjetoIntranet.Controllers
{
    public class MenuController : BaseController
    {
        public object StringWr { get; private set; }
      
        private CadastroMenuBO cmBO;

        private IList<CadastroMenu> linksDeMenu;

        private  List<CadastroMenu> ListaLinksFiltrados ;

        private static IList<SelectListItem> itens = new List<SelectListItem>();

        private HashSet<int> ordemUsuada = new HashSet<int>();

       private static StringWriter stringWriter = new StringWriter();
       private static  HtmlTextWriter htmlWriter = new HtmlTextWriter(stringWriter);

        
        [AllowAnonymous]
        public ActionResult SetCulture(string culture, string View)
        {

            culture = CultureHelper.GetImplementedCulture(culture);

            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);

            switch (View)
            {
                case "AdicionarLinks":
                    return RedirectToAction("AdicionarLinks");

                case "AssociarLinksEGrupos":
                    return RedirectToAction("AssociarLinksEGrupos");

                case "DesassociarLinksEGrupos":
                    return RedirectToAction("DesassociarLinksEGrupos");

                case "EditarMenu":
                    return RedirectToAction("EditarMenu");

                case "ListarLinks":
                    return RedirectToAction("ListarLinks");

                default: return RedirectToAction("Principal", "Home");

            }

        }


        [ChildActionOnly]
        public ActionResult MenuDinamico()  // responsavel por renderizar o menu na view enviando html
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;

            var usuarioLogado = Session["UsuarioLogado"] ;

            if (usuarioLogado.Equals(false)) // usar a flag de usuario para rederizar os links uma vez por usuario
            {
                Session.Remove("UsuarioLogado");

                Session.Add("UsuarioLogado", true);

                GrupoXMenuBO gXm = new GrupoXMenuBO();

                String MenuView = String.Empty;

              

                linksDeMenu = gXm.ListarPorGrupo(usr.getGrupos());



                Dictionary<int, ItemDeMenu> mapa = preencherMapa(linksDeMenu);


                List<ItemDeMenu> lista = preencherList(mapa);




                foreach (var item in lista)
                {
                    //if (item.pai == null)
                    //{


                       

                    //}
                    percorrer(item);

                }

            }

            


            
           
               
                return PartialView("_PartialDynamicMenu", (Object)stringWriter.ToString());

            
        }

        private Dictionary<int, ItemDeMenu> preencherMapa(IList<CadastroMenu> links) // responsavel por filtrar links repetidos fruto de uma intersecção entre gurpos
        {
            Dictionary<int, ItemDeMenu> mapa = new Dictionary<int, ItemDeMenu>(); 
           



            foreach (var item in links) 
            {


                ItemDeMenu i = new ItemDeMenu(); 

                i.id = item.id;  
                i.ordem = item.ordem;  
                i.nome = item.nome;  
                i.url = item.url;  

                mapa.Add(item.id, i);  


            }

           

            foreach (CadastroMenu entity in links) 
            {
               
                ItemDeMenu i = new ItemDeMenu();  

                i.id = entity.id; 
                i.ordem = entity.ordem;  
                i.nome = entity.nome;  
                i.url = entity.url;  

                if (!entity.codigoPai.Equals(0))  
                {
                    ItemDeMenu pai = new ItemDeMenu();  

                    mapa.TryGetValue(entity.codigoPai, out pai);  


                    pai.filhosList.Add(i);  
                    i.pai = pai;  


                }

               

                if (mapa.ContainsKey(entity.id))  
                {
                    ItemDeMenu it;  
                    mapa.TryGetValue(entity.id, out it);  



                    if (it.filhosList.Count == 0)  
                    {
                        mapa.Remove(entity.id);  
                        mapa.Add(entity.id, i);  

                    }
                    else
                    {

                        List<ItemDeMenu> temp = new List<ItemDeMenu>();  

                        foreach ( var item in it.filhosList)  
                        {
                            i.filhosList.Add(item);  

                        }

                        mapa.Remove(entity.id);  
                        mapa.Add(entity.id, i);  



                    }

                   

                }

            }
           

            return mapa;  //  1
        } 


        private static List<ItemDeMenu> preencherList(Dictionary<int, ItemDeMenu> mapa) // prepara uma lista de itens de menu
        {
            List<ItemDeMenu> itemlista = new List<ItemDeMenu>();

            foreach (var id in mapa.Keys)
            {

                ItemDeMenu it;
                    mapa.TryGetValue(id,out it);

                if (it.pai == null)
                {

                    itemlista.Add(it);

                }
               
            }



            return itemlista;

        }

        private static void percorrer(ItemDeMenu itemMenu) /// responsvale por percorres uma lista eceriar o codigo html para cada item de menu preparando para ser renderizado na view
        {


            htmlWriter.AddAttribute(HtmlTextWriterAttribute.Class, "li-menu"); 
            htmlWriter.RenderBeginTag(HtmlTextWriterTag.Li); 
            htmlWriter.AddAttribute(HtmlTextWriterAttribute.Href, itemMenu.url); 
            htmlWriter.RenderBeginTag(HtmlTextWriterTag.A); 
            htmlWriter.Write(itemMenu.nome); 
            htmlWriter.RenderEndTag(); //A  
            htmlWriter.RenderEndTag();//li  

            foreach (var item in itemMenu.filhosList) 
            {

                htmlWriter.RenderBeginTag(HtmlTextWriterTag.Ul); 

                percorrer(item); 

                htmlWriter.RenderEndTag();//ul//  
            }

        }

         [ChildActionOnly]
        public static void descarregar() // desaloca objetos em desuso
        {

            stringWriter.Dispose();
            htmlWriter.Dispose();

            stringWriter = new StringWriter();

            htmlWriter = new HtmlTextWriter(stringWriter);

        }

        

        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,TECNOLOGIA")]
        [HttpGet]
        public ActionResult EditarMenu() // responsavel por chamar a view editer menu
        {
            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;

            cmBO = new CadastroMenuBO();

            

            return View(cmBO.listaDeLinks());
        }

        [HttpPost]
        
         public ActionResult EditarMenu(String dados )
        {

            CadastroMenuBO cmBO = new CadastroMenuBO();

            List<CadastroMenu> listaDeLinks = null;

            listaDeLinks = JsonConvert.DeserializeObject<List<CadastroMenu>>(dados);

            Dictionary<int, CadastroMenu> conjunto = new Dictionary<int, CadastroMenu>();

            foreach (CadastroMenu item in listaDeLinks)
            {

                if (conjunto.ContainsKey(item.id))
                {

                    conjunto.Remove(item.id);

                    conjunto.Add(item.id, item);


                }
                else {

                    conjunto.Add(item.id, item);
                }

                
                
            }

            

            foreach (var valor in conjunto)
            {
               

                cmBO.Gravar(valor.Value);
               

            }
           

            return RedirectToAction("EditarMenu");
        }


       

        public JsonResult JsonLinksFilhos() // responsavel por retonar para view 
        {
            CadastroMenuBO cmBO = new CadastroMenuBO();

            return Json(cmBO.listaDeLinks(), JsonRequestBehavior.AllowGet);
        }

        

        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,TECNOLOGIA")]
        [HttpPost]
        public ActionResult AdicionarLinks(String link)
        {

            CadastroMenu cm = JsonConvert.DeserializeObject<CadastroMenu>(link);


            if(cm.nome != "" &&  cm.url != "")
            {

                CadastroMenuBO cmBO = new CadastroMenuBO();

                cmBO.Gravar(cm);

            }

                        

            return View();
        }
        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,TECNOLOGIA")]
        [HttpGet]
        public ActionResult AdicionarLinks()
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;



            return View();
        }

        [AutorizacaoCustomizada(Roles = "ADMINISTRADOR,TECNOLOGIA")]
        [HttpGet]
        public ActionResult ListarLinks()
        {

            Usuario usr = Session["UsuarioAtual"] as Usuario;


            ViewBag.UsuarioLogado = usr.nome;

            CadastroMenuBO cmBO = new CadastroMenuBO();

            

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="~/Resources/favicon.ico" type="image/x-icon" />
    @*<link rel="stylesheet" href="~/Content/font-awesome.min.css">*@
    <title>Intranet-Fênix</title>
    <link  rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
    <link rel="stylesheet" href="~/Content/Intra.css" type="text/css">

    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.9.2.custom.min.js")" type="text/javascript"></script>
    <link rel="stylesheet" href="~/Content/jquery-ui-1.9.2.custom.min" type="text/css">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        google.charts.load('current', { 'packages': ['corechart'] });

        // Set a callback to run when the Google Visualization API is loaded.
        google.charts.setOnLoadCallback(drawChart);

        // Callback that creates and populates a data table,
        // instantiates the pie chart, passes in the data and
        // draws it.
        function drawChart() {

            // Create the data table.
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Placas Mãe');
            data.addColumn('number', 'Quantidades');
            data.addRows([
                ['Placa 1', 3],
                ['Placa 2', 1],
                ['Placa 3', 1],
                ['Placa 4', 1],
                ['Placa 5', 2]
            ]);

            // Set chart options
            var options = {
                'title': 'Produção',
                'width': 300,
                'height': 230
            };

            // Instantiate and draw our chart, passing in some options.
            var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
            chart.draw(data, options);
        }
       

    </script>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/fonts/svg")
    @Styles.Render("~/Content/Intra")
    @Styles.Render("~/Content/Menu")


</head>
<body >
    <div class="layout">
        <header class="cabecalho">

            <div class="row fundo-nav">

                <div class="row over-fundo-nav">

                    <div class="col-md-6 col-sm-6 col-lg-6 ">

                        <div class="div-logo">

                            <img id="logo-intra" src="~/Resources/Logo-Negativada.png" alt="imagem11">

                        </div>



                    </div>


                    <div class="col-md-6  col-sm-6 col-lg-6 ">
                        <div class="container">

                            <div id="div-login" class="container">

                                <span style="color:wheat;"> @Recursos.Resources.BemVindo @ViewBag.UsuarioLogado !</span>

                                <a href="~/Home/LogOff">@Recursos.Resources.Sair</a>

                                <ul id="ul-links" class="nav ">
                                    <li class="item-141 toggle-contraste"><a class="toggle-contraste" href="#" accesskey="6">@Recursos.Resources.ALTO @Recursos.Resources.CONTRASTE</a></li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        <div class="row">

            <div class="col-md-3 col-sm-3 col-lg-3">

                <div id="container-menu-dinamico" class="container">


                    

                    @Html.Action("MenuDinamico", "Menu")


                     

                </div>

            </div>


            <div class="col-md-9 col-sm-9 col-lg-9">

                <div id="centro" class="container">

                    @RenderBody()
                    <br>


                </div>


            </div>




        </div>

        <div class="row">
            <div class="footer">
                <footer class="bloco-footer">

                    <div>

                        <br>

                    </div>


                </footer>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/Intranet")
        @Scripts.Render("~/bundles/NTM")


        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_PartialDetalhes.cshtml
@model ProjetoIntranet.Models.Entity.Curriculo
@Recursos.Resources.Culture



<h2>@Recursos.Resources.Detalhes</h2>

<div class="container">

    <td>
        @Html.DisplayFor(modelItem => modelItem.nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.cpf)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.estado.estado)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.area.cargo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.dataNascimento)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.uf)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.cep)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.cidade)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.bairro)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.rua)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.numero)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.descricao)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.telefoneFixo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.telefoneCelular)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.siteBlog)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.skype)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.remuneracao)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.genero)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.anexo.id)
    </td>



</div>

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_PartialDynamicMenu.cshtml
@*@model ProjetoIntranet.Models.Entity.CadastroMenu*@

@Recursos.Resources.Culture



<div class="container">


    <nav>
        
    </nav>


    <button id="botao-itens-menuDinamico" class="btn btn-navbar navbar-toggle collapsed" data-toggle="collapse" data-target="#tree-menu">

        <span id="icon-btn-lista" class="glyphicon glyphicon-th-list"></span>


    </button>

    <div class="tree-menu demo navbar-collapse collapse" id="tree-menu">

        <ul>

            @Html.Raw(@Model)

        </ul>

    </div>

</div>

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_PartialGraphView.cshtml
<html>
<head>
    <!--Load the AJAX API-->
   
    <script type="text/javascript"src="~/Scripts/Loader.js">




        // Load the Visualization API and the corechart package.
        google.charts.load('current', { 'packages': ['corechart'] });

        // Set a callback to run when the Google Visualization API is loaded.
        google.charts.setOnLoadCallback(drawChart);

        // Callback that creates and populates a data table,
        // instantiates the pie chart, passes in the data and
        // draws it.
        function drawChart(data) {

            // Create the data table.
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Topping');
            data.addColumn('number', 'Slices');
            
            
            // Set chart options
            var options = {
                'title': 'How Much Pizza I Ate Last Night',
                'width': 400,
                'height': 300
            };

            // Instantiate and draw our chart, passing in some options.
            var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
            chart.draw(data, options);
        }

        $(function () {

            $.ajax({

                type: 'GET',
                dataType: 'json',
                contentType: 'application/json',
                url: '@Url.Action("Graph2","Home")',
                data: '{}',
                success:
                function (data) {

                    drawChart(data);

                };

            });


        });

    </script>
</head>

<body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
</body>
</html>

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_PartialLista.cshtml
@model ProjetoIntranet.MV.MVlinkEGrupo
@Recursos.Resources.Culture

<div class="container">

    <table id="tb_links" class="display table">

        <thead>

            <tr>
                <th>@Recursos.Resources.ID</th>
                <th>@Recursos.Resources.Url</th>
                <th>@Recursos.Resources.Nome</th>
            </tr>

        </thead>

        <tbody id="tbCorpo"></tbody>

    </table>



</div>

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_PartialMenuView.cshtml
@model ProjetoIntranet.Models.Entity.CadastroMenu
@Recursos.Resources.Culture

@Styles.Render("~/Content/Menu")

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="layout">
    <div class="nav-side-menu">

        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

        <div class="menu-list">

            <ul id="menu-content" class="menu-content collapse out">
                <li>
                    <a href="#">
                        <i class="fa fa-dashboard fa-lg"></i> Dashboard
                    </a>
                </li>
                <li data-toggle="collapse" data-target="#products" class="collapsed active">
                    <a href="#"><i class="fa fa-gift fa-lg"></i> UI Elements <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                    <li class="active"><a href="#">CSS3 Animation</a></li>
                    <li><a href="#">General</a></li>
                    <li><a href="#">Buttons</a></li>
                    <li><a href="#">Tabs & Accordions</a></li>
                    <li><a href="#">Typography</a></li>
                    <li><a href="#">FontAwesome</a></li>
                    <li><a href="#">Slider</a></li>
                    <li><a href="#">Panels</a></li>
                    <li><a href="#">Widgets</a></li>
                    <li><a href="#">Bootstrap Model</a></li>
                </ul>

                <li data-toggle="collapse" data-target="#service" class="collapsed">
                    <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="service">
                    <li>New Service 1</li>
                    <li>New Service 2</li>
                    <li>New Service 3</li>
                </ul>

                <li data-toggle="collapse" data-target="#new" class="collapsed">
                    <a href="#"><i class="fa fa-car fa-lg"></i> New <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="new">
                    <li>New New 1</li>
                    <li>New New 2</li>
                    <li>New New 3</li>
                </ul>

                <li>
                    <a href="#">
                        <i class="fa fa-user fa-lg"></i> Profile
                    </a>
                </li>
                <li data-toggle="collapse" data-target="#grupos" class="collapsed">
                    <a href="#">
                        <i class="fa fa-users fa-lg"></i> Grupo de Usuarios <span class="arrow"></span>
                    </a>
                </li>
                <ul class="sub-menu collapse" id="grupos">
                    <li>@Html.ActionLink("Criar Grupo", "CriarGrupo", "GrupoUsuario")</li>
                    <li>@Html.ActionLink("Grupos Existentes", "ListarGrupos", "GrupoUsuario")</li>
                    <li>New New 3</li>
                </ul>

            </ul>
        </div>
    </div>
</div>

Extranet_Intranet-master/ProjetoIntranet/Views/Shared/_Rodape.cshtml
@model ProjetoIntranet.Models.Entity.MensagemEmail

<div class="footer">
    <div class="row">

        <div class="col-md-6  col-sm-6 col-lg-6">

            <h2 id="titulo1-footer" class="h2-format-footer"> @Recursos.Resources.Titulo6  </h2>


            <p id="texto1-footer" class="textos-format-footer">
               @Recursos.Resources.Endereco
               
                <a href="mailto:contato@hot.com" target="_blank" class="links-footer">contato.mg@foxconn.com </a>
            </p>
            <br>
            <p class="textos-format-footer"><a href="http://localhost:51573/Curriculo/Curriculo" class="links-footer">@Recursos.Resources.Titulo8 </a></p>
        </div>

        <div class="col-md-6  col-sm-6 col-lg-6">

            <h2 id="titulo2-footer" class="h2-format-footer">@Recursos.Resources.Titulo7 </h2>

            <div id="form-div">

                @using (@Html.BeginForm("Mensagem", "Home", FormMethod.Post, new { @class = "form-group" }))
            {

                    @Html.Label(@Recursos.Resources.Nome, new { @for = "nome" });
                    @Html.TextBox("nome", "", new { size = 30, @class = "form-control" });<br>
                    @Html.Label(@Recursos.Resources.Fone, new { @for = "fone" });
                    @Html.TextBox("fone", "", new { size = 30, @class = "form-control" });<br>
                    @Html.Label(@Recursos.Resources.Email, new { @for = "mail" });
                    @Html.TextBox("mail", "", new { size = 30, @class = "form-control" });<br>
                    @Html.Label("mensg", @Recursos.Resources.mensagem, new { @for = "msg" });
                    @Html.TextArea("msg", "", 5, 30, new { @class = "form-control" });<br>

                    <button id="btn-enviar" type="submit" class="btn btn-success">

                        <span class="glyphicon glyphicon-send"> Enviar </span>

                    </button>
                }

            </div>

        </div>

    </div>

</div>

<button id="top-btn" title="Subir ao topo" alt="subir ao topo"><span id="glyph-btn" class="glyphicon glyphicon-chevron-up"> </span></button>

<div id="pos-footer" class="row">
    <br>
    <br> <p id="texto-pos-footer"> Desenvolvido pelos alunos da FAI</p>
    <br>
</div>